import type {
  Patient,
  Consultation,
  Referral,
  Facility,
  ActionLogEntry,
  ChwPerformance,
  ZoneSummary,
  RiskLevel,
} from './types'

export const patients: Patient[] = [
  {
    id: 'p001',
    name: 'Abena Osei',
    age: 27,
    pathway: 'Pregnancy',
    riskLevel: 'HIGH',
    language: 'Twi',
    assignedChw: 'Grace Mensah',
    stage: '32 weeks',
    lastCallDate: '2026-05-27',
    registrationDate: '2025-12-10',
    riskHistory: [
      { date: '2025-12-10', level: 'LOW' },
      { date: '2026-03-15', level: 'MEDIUM' },
      { date: '2026-05-20', level: 'HIGH' },
    ],
    bloodPressure: '150/95 mmHg',
    kickCount: 8,
  },
  {
    id: 'p002',
    name: 'Efua Mensah',
    age: 31,
    pathway: 'Post-Loss',
    riskLevel: 'MEDIUM',
    language: 'Fante',
    assignedChw: 'Comfort Asante',
    stage: 'Post-loss: 4 months',
    lastCallDate: '2026-05-26',
    registrationDate: '2026-02-01',
    riskHistory: [
      { date: '2026-02-01', level: 'HIGH' },
      { date: '2026-04-10', level: 'MEDIUM' },
    ],
    copingIndex: 5,
    sleepQuality: 'Fair',
    bleedingStatus: 'None',
  },
  {
    id: 'p003',
    name: 'Akosua Addo',
    age: 23,
    pathway: 'Pregnancy',
    riskLevel: 'LOW',
    language: 'Twi',
    assignedChw: 'Grace Mensah',
    stage: '18 weeks',
    lastCallDate: '2026-05-25',
    registrationDate: '2026-01-20',
    riskHistory: [
      { date: '2026-01-20', level: 'LOW' },
    ],
    bloodPressure: '118/76 mmHg',
    kickCount: 12,
  },
  {
    id: 'p004',
    name: 'Ama Serwaa',
    age: 34,
    pathway: 'Pregnancy',
    riskLevel: 'HIGH',
    language: 'Twi',
    assignedChw: 'Comfort Asante',
    stage: '36 weeks',
    lastCallDate: '2026-05-28',
    registrationDate: '2025-09-15',
    riskHistory: [
      { date: '2025-09-15', level: 'MEDIUM' },
      { date: '2025-12-20', level: 'MEDIUM' },
      { date: '2026-04-01', level: 'HIGH' },
    ],
    bloodPressure: '160/100 mmHg',
    kickCount: 4,
  },
  {
    id: 'p005',
    name: 'Yaa Ansah',
    age: 26,
    pathway: 'Pregnancy',
    riskLevel: 'MEDIUM',
    language: 'Ga',
    assignedChw: 'Mercy Owusu',
    stage: '24 weeks',
    lastCallDate: '2026-05-24',
    registrationDate: '2025-11-30',
    riskHistory: [
      { date: '2025-11-30', level: 'LOW' },
      { date: '2026-03-20', level: 'MEDIUM' },
    ],
    bloodPressure: '135/88 mmHg',
    kickCount: 10,
  },
  {
    id: 'p006',
    name: 'Esi Naadu',
    age: 29,
    pathway: 'Post-Loss',
    riskLevel: 'LOW',
    language: 'Ewe',
    assignedChw: 'Mercy Owusu',
    stage: 'Post-loss: 8 months',
    lastCallDate: '2026-05-22',
    registrationDate: '2025-10-05',
    riskHistory: [
      { date: '2025-10-05', level: 'HIGH' },
      { date: '2025-12-15', level: 'MEDIUM' },
      { date: '2026-03-01', level: 'LOW' },
    ],
    copingIndex: 8,
    sleepQuality: 'Good',
    bleedingStatus: 'None',
  },
]

export const consultations: Consultation[] = [
  {
    id: 'c001',
    patientId: 'p001',
    patientName: 'Abena Osei',
    date: '2026-05-27',
    language: 'Twi',
    symptoms: ['severe headache', 'blurred vision', 'swollen feet'],
    riskLevel: 'HIGH',
    aiSummary:
      'Patient reports severe headache persisting for 3 days, blurred vision, and noticeable swelling in both feet. Blood pressure reading at 150/95 mmHg. These symptoms are consistent with pre-eclampsia warning signs. Immediate referral recommended.',
    transcript: [
      { speaker: 'AI', text: 'Mema wo akye Abena, wo ho te sen nnɛ? Masan ate sɛ wo ti pae wo.' },
      { speaker: 'Mother', text: "Me ho nnye koraa. Minya ti pae yi nnansa ni, ɛnna m'ani so repupuw me." },
      { speaker: 'AI', text: 'Wahu sɛ wo nan ahome/akuku anaa?' },
      { speaker: 'Mother', text: 'Aane, me nan abobow koraa.' },
      { speaker: 'AI', text: 'Mate aseɛ. Ɛsɛ sɛ wokɔ asopiti ntɛmara na yɛahwɛ wo ne wo ba no yie.' },
    ],
    triggeredReferral: true,
  },
  {
    id: 'c002',
    patientId: 'p002',
    patientName: 'Efua Mensah',
    date: '2026-05-26',
    language: 'Fante',
    symptoms: ['difficulty sleeping', 'persistent sadness', 'low appetite'],
    riskLevel: 'MEDIUM',
    aiSummary:
      'Patient continues to experience grief-related symptoms 4 months post-loss. Sleep quality has slightly improved from Poor to Fair. Coping index remains at 5/10. Recommend continued counselling sessions and community support group referral.',
    transcript: [
      { speaker: 'AI', text: 'Ibotae Efua? Wo ho te dɛn?' },
      { speaker: 'Mother', text: 'Hom nnye koraa. Menda yie, ɛnna medidi mpo a mempɛ.' },
      { speaker: 'AI', text: 'Mate ase. Ɛnnɛ wotumi kɔɔ counselling afahyɛ no bi?' },
      { speaker: 'Mother', text: 'Nyew, naaso nkabom no nnuru baabiara.' },
    ],
    triggeredReferral: false,
  },
  {
    id: 'c003',
    patientId: 'p003',
    patientName: 'Akosua Addo',
    date: '2026-05-25',
    language: 'Twi',
    symptoms: ['mild nausea', 'normal fatigue'],
    riskLevel: 'LOW',
    aiSummary:
      'Patient reports mild nausea and normal pregnancy-related fatigue at 18 weeks. Blood pressure stable at 118/76 mmHg. Baby kick count is within normal range. No danger signs identified. Continue routine ANC schedule.',
    transcript: [
      { speaker: 'AI', text: 'Maakye Akosua, wo ho te sen?' },
      { speaker: 'Mother', text: 'Me ho yɛ, nanso me bo repupuw me kakra.' },
      { speaker: 'AI', text: 'Ɛyɛ. Wo ba no tutu nso wote ne nka?' },
      { speaker: 'Mother', text: 'Aane, otutu yie paa.' },
    ],
    triggeredReferral: false,
  },
  {
    id: 'c004',
    patientId: 'p004',
    patientName: 'Ama Serwaa',
    date: '2026-05-28',
    language: 'Twi',
    symptoms: ['reduced fetal movement', 'severe abdominal pain', 'dizziness'],
    riskLevel: 'HIGH',
    aiSummary:
      'Patient at 36 weeks reports significantly reduced fetal movement (kick count: 4), severe abdominal pain, and episodes of dizziness. Blood pressure at 160/100 mmHg is critically elevated. URGENT: Immediate emergency referral activated for possible placental abruption.',
    transcript: [
      { speaker: 'AI', text: 'Ama, wo ho te dɛn? Ɛyɛ ya paa?' },
      { speaker: 'Mother', text: 'Me yam repae me paa. Bio nso, me ba no ntutu koraa te sɛ daa no.' },
      { speaker: 'AI', text: 'Ntɛmara, ɛsɛ sɛ wokɔ asopiti sesiaa. Mɛbɔ dawur ama ambulance abɛfa wo.' },
    ],
    triggeredReferral: true,
  },
  {
    id: 'c005',
    patientId: 'p005',
    patientName: 'Yaa Ansah',
    date: '2026-05-24',
    language: 'Ga',
    symptoms: ['mild back pain', 'occasional headaches'],
    riskLevel: 'MEDIUM',
    aiSummary:
      'Patient at 24 weeks reports mild back pain and occasional headaches. Blood pressure slightly elevated at 135/88 mmHg, warranting closer monitoring. No proteinuria detected. Scheduled for follow-up in 1 week.',
    transcript: [
      { speaker: 'AI', text: 'Teekpa Yaa, te oye tɛŋ?' },
      { speaker: 'Mother', text: 'Minaa hejɔlɛ yɛ mikwɛŋ, eye mipaŋ fioo nso.' },
      { speaker: 'AI', text: 'Eye kpakpa. Hɛɛ mɔ mɛni okyɛɛ kɛbashi otsi nyɔŋma loo?' },
      { speaker: 'Mother', text: 'Hɛɛ, mɛba dɔŋŋ otsi ni baa lɛ mli.' },
    ],
    triggeredReferral: false,
  },
  {
    id: 'c006',
    patientId: 'p006',
    patientName: 'Esi Naadu',
    date: '2026-05-22',
    language: 'Ewe',
    symptoms: ['improved mood', 'better sleep'],
    riskLevel: 'LOW',
    aiSummary:
      'Patient shows continued improvement 8 months post-loss. Coping index increased to 8/10. Sleep quality improved to Good. Actively participating in community support group. Recommend transitioning to quarterly check-ins.',
    transcript: [
      { speaker: 'AI', text: 'Ŋdi na wò Esi. Ɛfoa?' },
      { speaker: 'Mother', text: 'Mefo nyuie. Medɔ alɔ̃ nyuie, eye nye dzi nɔ fa fifia.' },
      { speaker: 'AI', text: 'Eyo, edze na wò! Míado go le ɣleti gbɔgbɔ mli.' },
    ],
    triggeredReferral: false,
  },
]

export const referrals: Referral[] = [
  {
    id: 'r001',
    patientId: 'p001',
    patientName: 'Abena Osei',
    riskLevel: 'HIGH',
    status: 'In Transit',
    facilityId: 'f001',
    facilityName: 'Korle-Bu Teaching Hospital',
    assignedChw: 'Grace Mensah',
    createdAt: '2026-05-27T09:30:00Z',
    timeline: [
      { stage: 'Referral Created', timestamp: '2026-05-27T09:30:00Z', note: 'Pre-eclampsia warning signs detected' },
      { stage: 'Ambulance Dispatched', timestamp: '2026-05-27T09:45:00Z' },
      { stage: 'In Transit', timestamp: '2026-05-27T10:00:00Z', note: 'ETA 25 minutes' },
    ],
  },
  {
    id: 'r002',
    patientId: 'p004',
    patientName: 'Ama Serwaa',
    riskLevel: 'HIGH',
    status: 'Pending',
    facilityId: 'f002',
    facilityName: 'Komfo Anokye Teaching Hospital',
    assignedChw: 'Comfort Asante',
    createdAt: '2026-05-28T08:15:00Z',
    timeline: [
      { stage: 'Referral Created', timestamp: '2026-05-28T08:15:00Z', note: 'Emergency: possible placental abruption at 36 weeks' },
    ],
  },
  {
    id: 'r003',
    patientId: 'p002',
    patientName: 'Efua Mensah',
    riskLevel: 'MEDIUM',
    status: 'Admitted',
    facilityId: 'f003',
    facilityName: 'Greater Accra Regional Hospital',
    assignedChw: 'Comfort Asante',
    outcome: 'Receiving grief counselling',
    createdAt: '2026-05-20T11:00:00Z',
    timeline: [
      { stage: 'Referral Created', timestamp: '2026-05-20T11:00:00Z', note: 'Counselling referral for grief management' },
      { stage: 'In Transit', timestamp: '2026-05-20T11:30:00Z' },
      { stage: 'Admitted', timestamp: '2026-05-20T12:15:00Z', note: 'Enrolled in intensive counselling programme' },
    ],
  },
  {
    id: 'r004',
    patientId: 'p003',
    patientName: 'Akosua Addo',
    riskLevel: 'LOW',
    status: 'Resolved',
    facilityId: 'f004',
    facilityName: 'Tamale Teaching Hospital',
    assignedChw: 'Grace Mensah',
    outcome: 'Routine check-up completed, all normal',
    createdAt: '2026-05-10T14:00:00Z',
    timeline: [
      { stage: 'Referral Created', timestamp: '2026-05-10T14:00:00Z', note: 'Routine ANC check-up' },
      { stage: 'In Transit', timestamp: '2026-05-10T14:20:00Z' },
      { stage: 'Admitted', timestamp: '2026-05-10T15:00:00Z' },
      { stage: 'Resolved', timestamp: '2026-05-10T16:30:00Z', note: 'All vitals normal, follow-up in 4 weeks' },
    ],
  },
]

export const facilities: Facility[] = [
  {
    id: 'f001',
    name: 'Korle-Bu Teaching Hospital',
    distance: '2.8 km',
    hours: '24/7 Emergency',
    services: ['Obstetrics', 'Neonatal ICU', 'Emergency', 'Laboratory', 'Ultrasound'],
    phone: '+233-30-267-3000',
    address: 'Guggisberg Avenue, Korle Gonno, Accra',
  },
  {
    id: 'f002',
    name: 'Komfo Anokye Teaching Hospital',
    distance: '5.4 km',
    hours: '24/7 Emergency',
    services: ['Obstetrics', 'Gynaecology', 'Neonatal ICU', 'Surgery', 'Blood Bank', 'Emergency'],
    phone: '+233-32-202-2301',
    address: 'Bantama High Street, Bantama, Kumasi',
  },
  {
    id: 'f003',
    name: 'Greater Accra Regional Hospital',
    distance: '4.2 km',
    hours: '24/7 Emergency',
    services: ['Obstetrics', 'Mental Health', 'Social Work', 'Counselling', 'Laboratory'],
    phone: '+233-30-222-8315',
    address: 'Castle Road, Ridge, Accra',
  },
  {
    id: 'f004',
    name: 'Tamale Teaching Hospital',
    distance: '9.1 km',
    hours: 'Mon-Sat 7AM-9PM, Emergency 24/7',
    services: ['Obstetrics', 'Paediatrics', 'Emergency', 'Laboratory', 'Ultrasound'],
    phone: '+233-37-202-2415',
    address: 'Hospital Road, Tamale',
  },
]

export const actionLog: ActionLogEntry[] = [
  {
    id: 'a001',
    patientId: 'p001',
    type: 'Alert',
    description: 'Risk level escalated to HIGH — pre-eclampsia warning signs detected during AI consultation',
    timestamp: '2026-05-27T09:28:00Z',
    performedBy: 'System',
  },
  {
    id: 'a002',
    patientId: 'p001',
    type: 'Referral',
    description: 'Emergency referral created to Korle-Bu Teaching Hospital',
    timestamp: '2026-05-27T09:30:00Z',
    performedBy: 'Grace Mensah',
  },
  {
    id: 'a003',
    patientId: 'p004',
    type: 'Alert',
    description: 'Risk level escalated to HIGH — reduced fetal movement and critically elevated blood pressure (160/100)',
    timestamp: '2026-05-28T08:12:00Z',
    performedBy: 'System',
  },
  {
    id: 'a004',
    patientId: 'p004',
    type: 'Referral',
    description: 'Emergency referral created to Komfo Anokye Teaching Hospital — possible placental abruption',
    timestamp: '2026-05-28T08:15:00Z',
    performedBy: 'Comfort Asante',
  },
  {
    id: 'a005',
    patientId: 'p002',
    type: 'Call',
    description: 'Follow-up call completed — patient reports continued grief symptoms, coping index unchanged at 5/10',
    timestamp: '2026-05-26T10:00:00Z',
    performedBy: 'Comfort Asante',
  },
  {
    id: 'a006',
    patientId: 'p003',
    type: 'Visit',
    description: 'Routine ANC visit completed — all vitals normal, pregnancy progressing well at 18 weeks',
    timestamp: '2026-05-25T14:00:00Z',
    performedBy: 'Grace Mensah',
  },
  {
    id: 'a007',
    patientId: 'p005',
    type: 'Vitals',
    description: 'Blood pressure slightly elevated at 135/88 mmHg during routine check — scheduled follow-up in 1 week',
    timestamp: '2026-05-24T11:30:00Z',
    performedBy: 'Mercy Owusu',
  },
  {
    id: 'a008',
    patientId: 'p006',
    type: 'Outcome',
    description: 'Quarterly review — coping index improved to 8/10, sleep quality rated Good. Transitioning to quarterly check-ins',
    timestamp: '2026-05-22T09:00:00Z',
    performedBy: 'Mercy Owusu',
  },
  {
    id: 'a009',
    patientId: 'p001',
    type: 'Vitals',
    description: 'Blood pressure reading: 150/95 mmHg — above normal range',
    timestamp: '2026-05-27T09:25:00Z',
    performedBy: 'System',
  },
  {
    id: 'a010',
    patientId: 'p004',
    type: 'Registration',
    description: 'Patient registered for MamaCare programme — high-risk pregnancy, age 34',
    timestamp: '2025-09-15T08:00:00Z',
    performedBy: 'Comfort Asante',
  },
]

export const chwPerformanceData: ChwPerformance[] = [
  {
    chwName: 'Grace Mensah',
    totalCases: 2,
    followUpRate: 95,
    resolvedCases: 0,
    activeCases: 2,
  },
  {
    chwName: 'Comfort Asante',
    totalCases: 2,
    followUpRate: 88,
    resolvedCases: 1,
    activeCases: 1,
  },
  {
    chwName: 'Mercy Owusu',
    totalCases: 2,
    followUpRate: 92,
    resolvedCases: 1,
    activeCases: 1,
  },
]

export const zoneSummary: ZoneSummary = {
  caseload: 6,
  pendingVisits: 4,
  unresolvedDanger: 2,
}

export const riskEscalationFeed: { patientId: string; patientName: string; fromLevel: RiskLevel; toLevel: RiskLevel; date: string; reason: string }[] = [
  {
    patientId: 'p001',
    patientName: 'Abena Osei',
    fromLevel: 'MEDIUM',
    toLevel: 'HIGH',
    date: '2026-05-20',
    reason: 'Pre-eclampsia warning signs: severe headache, blurred vision, elevated BP 150/95',
  },
  {
    patientId: 'p004',
    patientName: 'Ama Serwaa',
    fromLevel: 'MEDIUM',
    toLevel: 'HIGH',
    date: '2026-04-01',
    reason: 'Persistently elevated blood pressure at 36 weeks gestation',
  },
  {
    patientId: 'p005',
    patientName: 'Yaa Ansah',
    fromLevel: 'LOW',
    toLevel: 'MEDIUM',
    date: '2026-03-20',
    reason: 'Blood pressure trending upward, mild headaches reported',
  },
  {
    patientId: 'p002',
    patientName: 'Efua Mensah',
    fromLevel: 'HIGH',
    toLevel: 'MEDIUM',
    date: '2026-04-10',
    reason: 'Coping index improved from 3 to 5, sleep quality improved to Fair',
  },
  {
    patientId: 'p006',
    patientName: 'Esi Naadu',
    fromLevel: 'MEDIUM',
    toLevel: 'LOW',
    date: '2026-03-01',
    reason: 'Consistent improvement in coping index and sleep quality over 5 months',
  },
]

export const kpiData = {
  totalMothers: 6,
  highRisk: 2,
  pendingActions: 4,
  resolutionRate: 78,
}
