import type {
  Patient,
  Consultation,
  Referral,
  Facility,
  ActionLogEntry,
  ChwPerformance,
  ZoneSummary,
  RiskLevel,
} from './types'

export const patients: Patient[] = [
  {
    id: 'p001',
    name: 'Amina Ibrahim',
    age: 27,
    pathway: 'Pregnancy',
    riskLevel: 'HIGH',
    language: 'Hausa',
    assignedChw: 'Hadiza Bello',
    stage: '32 weeks',
    lastCallDate: '2026-05-27',
    registrationDate: '2025-12-10',
    riskHistory: [
      { date: '2025-12-10', level: 'LOW' },
      { date: '2026-03-15', level: 'MEDIUM' },
      { date: '2026-05-20', level: 'HIGH' },
    ],
    bloodPressure: '150/95 mmHg',
    kickCount: 8,
  },
  {
    id: 'p002',
    name: 'Chloe Adeyemi',
    age: 31,
    pathway: 'Post-Loss',
    riskLevel: 'MEDIUM',
    language: 'Yoruba',
    assignedChw: 'Funke Alabi',
    stage: 'Post-loss: 4 months',
    lastCallDate: '2026-05-26',
    registrationDate: '2026-02-01',
    riskHistory: [
      { date: '2026-02-01', level: 'HIGH' },
      { date: '2026-04-10', level: 'MEDIUM' },
    ],
    copingIndex: 5,
    sleepQuality: 'Fair',
    bleedingStatus: 'None',
  },
  {
    id: 'p003',
    name: 'Fatima Okonkwo',
    age: 23,
    pathway: 'Pregnancy',
    riskLevel: 'LOW',
    language: 'Igbo',
    assignedChw: 'Ngozi Eze',
    stage: '18 weeks',
    lastCallDate: '2026-05-25',
    registrationDate: '2026-01-20',
    riskHistory: [
      { date: '2026-01-20', level: 'LOW' },
    ],
    bloodPressure: '118/76 mmHg',
    kickCount: 12,
  },
  {
    id: 'p004',
    name: 'Adama Musa',
    age: 34,
    pathway: 'Pregnancy',
    riskLevel: 'HIGH',
    language: 'Hausa',
    assignedChw: 'Hadiza Bello',
    stage: '36 weeks',
    lastCallDate: '2026-05-28',
    registrationDate: '2025-09-15',
    riskHistory: [
      { date: '2025-09-15', level: 'MEDIUM' },
      { date: '2025-12-20', level: 'MEDIUM' },
      { date: '2026-04-01', level: 'HIGH' },
    ],
    bloodPressure: '160/100 mmHg',
    kickCount: 4,
  },
  {
    id: 'p005',
    name: 'Ngochi Nwankwo',
    age: 26,
    pathway: 'Pregnancy',
    riskLevel: 'MEDIUM',
    language: 'Igbo',
    assignedChw: 'Ngozi Eze',
    stage: '24 weeks',
    lastCallDate: '2026-05-24',
    registrationDate: '2025-11-30',
    riskHistory: [
      { date: '2025-11-30', level: 'LOW' },
      { date: '2026-03-20', level: 'MEDIUM' },
    ],
    bloodPressure: '135/88 mmHg',
    kickCount: 10,
  },
  {
    id: 'p006',
    name: 'Bisi Ogunleye',
    age: 29,
    pathway: 'Post-Loss',
    riskLevel: 'LOW',
    language: 'Yoruba',
    assignedChw: 'Funke Alabi',
    stage: 'Post-loss: 8 months',
    lastCallDate: '2026-05-22',
    registrationDate: '2025-10-05',
    riskHistory: [
      { date: '2025-10-05', level: 'HIGH' },
      { date: '2025-12-15', level: 'MEDIUM' },
      { date: '2026-03-01', level: 'LOW' },
    ],
    copingIndex: 8,
    sleepQuality: 'Good',
    bleedingStatus: 'None',
  },
]

export const consultations: Consultation[] = [
  {
    id: 'c001',
    patientId: 'p001',
    patientName: 'Amina Ibrahim',
    date: '2026-05-27',
    language: 'Hausa',
    symptoms: ['severe headache', 'blurred vision', 'swollen feet'],
    riskLevel: 'HIGH',
    aiSummary:
      'Patient reports severe headache persisting for 3 days, blurred vision, and noticeable swelling in both feet. Blood pressure reading at 150/95 mmHg. These symptoms are consistent with pre-eclampsia warning signs. Immediate referral recommended.',
    transcript: [
      { speaker: 'AI', text: 'Sannu Amina, yaya lafiyar ku a yau? Na ji labarin ciwon kai ku.' },
      { speaker: 'Mother', text: 'Lafiya ba ta da kyau. Na ci ciwon kai na tsawon kwanaki uku kuma na ga abubuwa ba su da kyau.' },
      { speaker: 'AI', text: 'Kuna ganin wani canji a kafafu ku?' },
      { speaker: 'Mother', text: 'Ee, kafafu na sun kumbura sosai.' },
      { speaker: 'AI', text: 'Na gane matsalar. Zan tura ku asibiti da sauri don duba lafiyar ku da jaririn ku.' },
    ],
    triggeredReferral: true,
  },
  {
    id: 'c002',
    patientId: 'p002',
    patientName: 'Chloe Adeyemi',
    date: '2026-05-26',
    language: 'Yoruba',
    symptoms: ['difficulty sleeping', 'persistent sadness', 'low appetite'],
    riskLevel: 'MEDIUM',
    aiSummary:
      'Patient continues to experience grief-related symptoms 4 months post-loss. Sleep quality has slightly improved from Poor to Fair. Coping index remains at 5/10. Recommend continued counselling sessions and community support group referral.',
    transcript: [
      { speaker: 'AI', text: 'Bawo ni Chloe? Se alafia ni?' },
      { speaker: 'Mother', text: 'Eeyan ko too daadaa. Ojo oniruuru ti n sun, ati pe erin pe mi.' },
      { speaker: 'AI', text: 'Mo royin re. Se o ti lo ibi ipadanu to gba ni?' },
      { speaker: 'Mother', text: 'Bee ni, sugbon ko too pese atilereyin to un se.' },
    ],
    triggeredReferral: false,
  },
  {
    id: 'c003',
    patientId: 'p003',
    patientName: 'Fatima Okonkwo',
    date: '2026-05-25',
    language: 'Igbo',
    symptoms: ['mild nausea', 'normal fatigue'],
    riskLevel: 'LOW',
    aiSummary:
      'Patient reports mild nausea and normal pregnancy-related fatigue at 18 weeks. Blood pressure stable at 118/76 mmHg. Baby kick count is within normal range. No danger signs identified. Continue routine ANC schedule.',
    transcript: [
      { speaker: 'AI', text: 'Nno Fatima, kedu ka i mere?' },
      { speaker: 'Mother', text: 'A dim mma, mana na-enwe mgbe ụfọdụ na-eso nri.' },
      { speaker: 'AI', text: 'O dị mma. Gbasara ịma nwa, ị na-ahụkwaghị ọgba aghara?' },
      { speaker: 'Mother', text: 'Mba, nwa na-agagharị nke ọma.' },
    ],
    triggeredReferral: false,
  },
  {
    id: 'c004',
    patientId: 'p004',
    patientName: 'Adama Musa',
    date: '2026-05-28',
    language: 'Hausa',
    symptoms: ['reduced fetal movement', 'severe abdominal pain', 'dizziness'],
    riskLevel: 'HIGH',
    aiSummary:
      'Patient at 36 weeks reports significantly reduced fetal movement (kick count: 4), severe abdominal pain, and episodes of dizziness. Blood pressure at 160/100 mmHg is critically elevated. URGENT: Immediate emergency referral activated for possible placental abruption.',
    transcript: [
      { speaker: 'AI', text: 'Adama, yaya lafiyar ku? Kai tsanani ne?' },
      { speaker: 'Mother', text: 'Ina jin zafi mai tsanani a ciki. Kuma jaririn baya motsawa kamar yadda ya saba.' },
      { speaker: 'AI', text: 'Da sauri, muna bukatar ku je asibiti nan take. Zan tura muku agajin gaggawa.' },
    ],
    triggeredReferral: true,
  },
  {
    id: 'c005',
    patientId: 'p005',
    patientName: 'Ngochi Nwankwo',
    date: '2026-05-24',
    language: 'Igbo',
    symptoms: ['mild back pain', 'occasional headaches'],
    riskLevel: 'MEDIUM',
    aiSummary:
      'Patient at 24 weeks reports mild back pain and occasional headaches. Blood pressure slightly elevated at 135/88 mmHg, warranting closer monitoring. No proteinuria detected. Scheduled for follow-up in 1 week.',
    transcript: [
      { speaker: 'AI', text: 'Ndeewo Ngochi, kedu ka ahụ ike dị?' },
      { speaker: 'Mother', text: 'O siri ike n\'ukwu azụ m, ma na-enwe isi ọma ụfọdụ.' },
      { speaker: 'AI', text: 'Anyị ga-achọ iso gi gbaa mbọ. Biko bịa ọzọ n\'izu na-abịa.' },
    ],
    triggeredReferral: false,
  },
  {
    id: 'c006',
    patientId: 'p006',
    patientName: 'Bisi Ogunleye',
    date: '2026-05-22',
    language: 'Yoruba',
    symptoms: ['improved mood', 'better sleep'],
    riskLevel: 'LOW',
    aiSummary:
      'Patient shows continued improvement 8 months post-loss. Coping index increased to 8/10. Sleep quality improved to Good. Actively participating in community support group. Recommend transitioning to quarterly check-ins.',
    transcript: [
      { speaker: 'AI', text: 'Bawo ni Bisi? Nibo lo wa loni?' },
      { speaker: 'Mother', text: 'Mo d\'ara pupọ nisisiyi. Sun mi dara, ati pe mo nifẹ si awọn iṣẹ ṣiṣe.' },
      { speaker: 'AI', text: 'Eyi n dara! A o pade ni osu to nbo.' },
    ],
    triggeredReferral: false,
  },
]

export const referrals: Referral[] = [
  {
    id: 'r001',
    patientId: 'p001',
    patientName: 'Amina Ibrahim',
    riskLevel: 'HIGH',
    status: 'In Transit',
    facilityId: 'f001',
    facilityName: 'Maitama District Hospital',
    assignedChw: 'Hadiza Bello',
    createdAt: '2026-05-27T09:30:00Z',
    timeline: [
      { stage: 'Referral Created', timestamp: '2026-05-27T09:30:00Z', note: 'Pre-eclampsia warning signs detected' },
      { stage: 'Ambulance Dispatched', timestamp: '2026-05-27T09:45:00Z' },
      { stage: 'In Transit', timestamp: '2026-05-27T10:00:00Z', note: 'ETA 25 minutes' },
    ],
  },
  {
    id: 'r002',
    patientId: 'p004',
    patientName: 'Adama Musa',
    riskLevel: 'HIGH',
    status: 'Pending',
    facilityId: 'f002',
    facilityName: 'National Hospital Abuja',
    assignedChw: 'Hadiza Bello',
    createdAt: '2026-05-28T08:15:00Z',
    timeline: [
      { stage: 'Referral Created', timestamp: '2026-05-28T08:15:00Z', note: 'Emergency: possible placental abruption at 36 weeks' },
    ],
  },
  {
    id: 'r003',
    patientId: 'p002',
    patientName: 'Chloe Adeyemi',
    riskLevel: 'MEDIUM',
    status: 'Admitted',
    facilityId: 'f003',
    facilityName: 'Lagos University Teaching Hospital',
    assignedChw: 'Funke Alabi',
    outcome: 'Receiving grief counselling',
    createdAt: '2026-05-20T11:00:00Z',
    timeline: [
      { stage: 'Referral Created', timestamp: '2026-05-20T11:00:00Z', note: 'Counselling referral for grief management' },
      { stage: 'In Transit', timestamp: '2026-05-20T11:30:00Z' },
      { stage: 'Admitted', timestamp: '2026-05-20T12:15:00Z', note: 'Enrolled in intensive counselling programme' },
    ],
  },
  {
    id: 'r004',
    patientId: 'p003',
    patientName: 'Fatima Okonkwo',
    riskLevel: 'LOW',
    status: 'Resolved',
    facilityId: 'f004',
    facilityName: 'Enugu State University Teaching Hospital',
    assignedChw: 'Ngozi Eze',
    outcome: 'Routine check-up completed, all normal',
    createdAt: '2026-05-10T14:00:00Z',
    timeline: [
      { stage: 'Referral Created', timestamp: '2026-05-10T14:00:00Z', note: 'Routine ANC check-up' },
      { stage: 'In Transit', timestamp: '2026-05-10T14:20:00Z' },
      { stage: 'Admitted', timestamp: '2026-05-10T15:00:00Z' },
      { stage: 'Resolved', timestamp: '2026-05-10T16:30:00Z', note: 'All vitals normal, follow-up in 4 weeks' },
    ],
  },
]

export const facilities: Facility[] = [
  {
    id: 'f001',
    name: 'Maitama District Hospital',
    distance: '3.2 km',
    hours: '24/7 Emergency',
    services: ['Obstetrics', 'Neonatal ICU', 'Emergency', 'Laboratory', 'Ultrasound'],
    phone: '+234-9-5230-000',
    address: 'Umaru Musa Yar\'Adua Way, Maitama, Abuja',
  },
  {
    id: 'f002',
    name: 'National Hospital Abuja',
    distance: '5.8 km',
    hours: '24/7 Emergency',
    services: ['Obstetrics', 'Gynaecology', 'Neonatal ICU', 'Surgery', 'Blood Bank', 'Emergency'],
    phone: '+234-9-5240-000',
    address: 'Independence Avenue, Central District, Abuja',
  },
  {
    id: 'f003',
    name: 'Lagos University Teaching Hospital',
    distance: '12.1 km',
    hours: '24/7 Emergency',
    services: ['Obstetrics', 'Mental Health', 'Social Work', 'Counselling', 'Laboratory'],
    phone: '+234-1-5850-000',
    address: 'Idi-Araba, Surulere, Lagos',
  },
  {
    id: 'f004',
    name: 'Enugu State University Teaching Hospital',
    distance: '7.4 km',
    hours: 'Mon-Sat 7AM-9PM, Emergency 24/7',
    services: ['Obstetrics', 'Paediatrics', 'Emergency', 'Laboratory', 'Ultrasound'],
    phone: '+234-42-2530-000',
    address: 'Park Lane, GRA, Enugu',
  },
]

export const actionLog: ActionLogEntry[] = [
  {
    id: 'a001',
    patientId: 'p001',
    type: 'Alert',
    description: 'Risk level escalated to HIGH — pre-eclampsia warning signs detected during AI consultation',
    timestamp: '2026-05-27T09:28:00Z',
    performedBy: 'System',
  },
  {
    id: 'a002',
    patientId: 'p001',
    type: 'Referral',
    description: 'Emergency referral created to Maitama District Hospital',
    timestamp: '2026-05-27T09:30:00Z',
    performedBy: 'Hadiza Bello',
  },
  {
    id: 'a003',
    patientId: 'p004',
    type: 'Alert',
    description: 'Risk level escalated to HIGH — reduced fetal movement and critically elevated blood pressure (160/100)',
    timestamp: '2026-05-28T08:12:00Z',
    performedBy: 'System',
  },
  {
    id: 'a004',
    patientId: 'p004',
    type: 'Referral',
    description: 'Emergency referral created to National Hospital Abuja — possible placental abruption',
    timestamp: '2026-05-28T08:15:00Z',
    performedBy: 'Hadiza Bello',
  },
  {
    id: 'a005',
    patientId: 'p002',
    type: 'Call',
    description: 'Follow-up call completed — patient reports continued grief symptoms, coping index unchanged at 5/10',
    timestamp: '2026-05-26T10:00:00Z',
    performedBy: 'Funke Alabi',
  },
  {
    id: 'a006',
    patientId: 'p003',
    type: 'Visit',
    description: 'Routine ANC visit completed — all vitals normal, pregnancy progressing well at 18 weeks',
    timestamp: '2026-05-25T14:00:00Z',
    performedBy: 'Ngozi Eze',
  },
  {
    id: 'a007',
    patientId: 'p005',
    type: 'Vitals',
    description: 'Blood pressure slightly elevated at 135/88 mmHg during routine check — scheduled follow-up in 1 week',
    timestamp: '2026-05-24T11:30:00Z',
    performedBy: 'Ngozi Eze',
  },
  {
    id: 'a008',
    patientId: 'p006',
    type: 'Outcome',
    description: 'Quarterly review — coping index improved to 8/10, sleep quality rated Good. Transitioning to quarterly check-ins',
    timestamp: '2026-05-22T09:00:00Z',
    performedBy: 'Funke Alabi',
  },
  {
    id: 'a009',
    patientId: 'p001',
    type: 'Vitals',
    description: 'Blood pressure reading: 150/95 mmHg — above normal range',
    timestamp: '2026-05-27T09:25:00Z',
    performedBy: 'System',
  },
  {
    id: 'a010',
    patientId: 'p004',
    type: 'Registration',
    description: 'Patient registered for MamaCare programme — high-risk pregnancy, age 34',
    timestamp: '2025-09-15T08:00:00Z',
    performedBy: 'Hadiza Bello',
  },
]

export const chwPerformanceData: ChwPerformance[] = [
  {
    chwName: 'Hadiza Bello',
    totalCases: 2,
    followUpRate: 95,
    resolvedCases: 0,
    activeCases: 2,
  },
  {
    chwName: 'Funke Alabi',
    totalCases: 2,
    followUpRate: 88,
    resolvedCases: 1,
    activeCases: 1,
  },
  {
    chwName: 'Ngozi Eze',
    totalCases: 2,
    followUpRate: 92,
    resolvedCases: 1,
    activeCases: 1,
  },
]

export const zoneSummary: ZoneSummary = {
  caseload: 6,
  pendingVisits: 4,
  unresolvedDanger: 2,
}

export const riskEscalationFeed: { patientId: string; patientName: string; fromLevel: RiskLevel; toLevel: RiskLevel; date: string; reason: string }[] = [
  {
    patientId: 'p001',
    patientName: 'Amina Ibrahim',
    fromLevel: 'MEDIUM',
    toLevel: 'HIGH',
    date: '2026-05-20',
    reason: 'Pre-eclampsia warning signs: severe headache, blurred vision, elevated BP 150/95',
  },
  {
    patientId: 'p004',
    patientName: 'Adama Musa',
    fromLevel: 'MEDIUM',
    toLevel: 'HIGH',
    date: '2026-04-01',
    reason: 'Persistently elevated blood pressure at 36 weeks gestation',
  },
  {
    patientId: 'p005',
    patientName: 'Ngochi Nwankwo',
    fromLevel: 'LOW',
    toLevel: 'MEDIUM',
    date: '2026-03-20',
    reason: 'Blood pressure trending upward, mild headaches reported',
  },
  {
    patientId: 'p002',
    patientName: 'Chloe Adeyemi',
    fromLevel: 'HIGH',
    toLevel: 'MEDIUM',
    date: '2026-04-10',
    reason: 'Coping index improved from 3 to 5, sleep quality improved to Fair',
  },
  {
    patientId: 'p006',
    patientName: 'Bisi Ogunleye',
    fromLevel: 'MEDIUM',
    toLevel: 'LOW',
    date: '2026-03-01',
    reason: 'Consistent improvement in coping index and sleep quality over 5 months',
  },
]

export const kpiData = {
  totalMothers: 6,
  highRisk: 2,
  pendingActions: 4,
  resolutionRate: 78,
}
